### ISSUE TITLE
Ansible-galaxy

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#10]
It would be great to add this playbook to Ansible Galaxy as Roman suggested.
But @brainstorm, have you already done it?
You added to the doc `ansible-galaxy install nimiq.ansible-biostar` but I actually cannot find it on Galaxy, so I guess you didn't right?

**Comment by brainstorm** [comment]
No, I did not, since you are the author you should get an account on ansible galaxy and connect it to your github repo ;)

**Comment by puntonim** [comment]
Done: https://galaxy.ansible.com/list#/roles/1057
