### ISSUE TITLE
Cloud-agnostic deployment

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#11]
We want to be able to deploy to different cloud services.

@brainstorm suggests something like:

```
ansible-playbook site.yml --extra-vars "cloud_provider=aws aws_access_key=..."
ansible-playbook site.yml --extra-vars="cloud_provider=gce gce_service_email=..."
```

But, why not the following?

```
ansible-playbook aws.yml --extra-vars "aws_access_key=..."
ansible-playbook gce.yml --extra-vars="gce_service_email=..."
```

**Comment by brainstorm** [comment]
Good call, it does seem cleaner from user perspective. Then calling `site.yml` from `gce.yml` and `aws.yml`, right?

**Comment by puntonim** [comment]
I would get rid of `site.yml` because this name is too generic in this case. And I'll add/edit `aws.yml` and `gce.yml` such that they start and provision a new machine first and then they call `biostar.yml`. I'll do it when I'm done with other high priority things.

**Comment by brainstorm** [comment]
The reason why I chose to stick with `site.yml` is because it's stated on Ansible's best practice docs:

http://docs.ansible.com/playbooks_best_practices.html#directory-layout

In order to comply with the "least surprise" principle, I would keep `site.yml` anyway, but I'll ask around and see what the community has to say about that.

**Comment by brainstorm** [comment]
RT == <3

https://twitter.com/braincode/status/481041753093734400

**Comment by brainstorm** [comment]
@nimiq, In case you missed it, here's the response of the actual main author of Ansible, Michael Dehaan:

https://groups.google.com/forum/#!topic/ansible-project/WWRit56iYrg

**Comment by puntonim** [comment]
Ok, Michael recommends to keep the provisioning playbooks separate. Which means the solution I proposed or 2 different GitHub repos? Did you get that @brainstorm?

**Comment by puntonim** [comment]
Done https://github.com/nimiq/ansible-biostar/commit/c8bd0a49c7b1536abe8f18519d713db94d8b593d
