### ISSUE TITLE
Staging.neurostars.org domain

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#15]
staging.neurostars.org must point to our staging EC2 instance.
We often destroy this instance and launch a new one with a new IP address and updating the DNS takes many hours.

Solution:
- use a Amazon elastic IP, but it's not for free if the machine is not running;
- use a 2-step redirect: use DtDNS to assign a (sub-)domain like `staging-neurostars.dtdns.net` to the EC2 instance (and keep it updated manually or via a script) then redirect `staging.neurostars.org` to `staging-neurostars.dtdns.net`.
  The second solution is a bit of a dirty hack, but as it is only for staging and it is free, I guess is the best.

**Comment by puntonim** [comment]
The dynamic domain is up: http://staging-neurostars.dtdns.net/

TODO:
- [x] add a way to allow multiple domains in Nginx and Django (this is a cool feature apart from this specific issue, I already know how to do it);
- [x] redirect `staging.neurostars.org` to `staging-neurostars.dtdns.net`

**Comment by brainstorm** [comment]
I just defined `staging.neurostars.org` as a `CNAME` for `staging-neurostars.dtdns.net`. If that does not work, we can just go for EIPs.

Please close the issue or assign me as a repo collaborator.

**Comment by puntonim** [comment]
Now you are a collaborator. But wait before closing this, I'd like to add a way to allow multiple domains in Nginx and Django, it is a quick thing.
