### ISSUE TITLE
Social provider logins in staging

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#16]
Seems they are broken, it should be a matter of callback urls.

**Comment by brainstorm** [comment]
I guess that the URL redirect hack does not play well with it. Just use persona for staging for now, it does not require all the Oauth tokens dance...

**Comment by puntonim** [comment]
If I remember well, this problem is older than the redirect thing and Google currently says: "http://staging.neurostars.org/accounts/google/login/callback/ did not match a registered redirect URI". So it really seems a matter of callback urls.

**Comment by brainstorm** [comment]
My point was that other than having to debug this particular OAuth extensions on staging, you can just use mozilla persona, which works flawlessly locally, on staging and in production. No maintenance needed.

BTW, speaking of `django-allauth`, how is ORCID going? Need some help?

**Comment by puntonim** [comment]
I haven't started with ORCID yet. I'm working on Travis-CI today.

**Comment by brainstorm** [comment]
Alright, let me know if you need some pointers on Travis too. Here's an example of a Travis-CI yml file we wrote on my previous job:

https://github.com/SciLifeLab/bcbb/blob/master/.travis.yml
