### ISSUE TITLE
Add a cron schedule to rebuild index

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#2]
We are using whoosh as full text search engine. It requires a cron schedule to rebuild the index.
F.i. every 10 min:

```
source conf/default.env
source conf/docker.env
biostar.sh update_index
```

**Comment by brainstorm** [comment]
https://pythonhosted.org/plan/

**Comment by puntonim** [comment]
Done 5ccd7a6203f7f14cc53e6dd57f3d42e086d9214f
