### ISSUE TITLE
General deployment code review

### ISSUE THREAD

**Issue by brainstorm** [puntonim/ansible-biostar#3]
Yeah! Excellent job indeed @nimiq!

Your EC2 rewrite definitely looks much nicer than my cloudformation approach, kudos for that!

Here are minor issues that I think should be addressed:
- [x] As much as you can, avoid storing data inside the containers, as pointed out in the Docker misconception guidelines ('Don't store data in containers'): https://devopsu.com/blog/docker-misconceptions/
- [x] Open ports for ELK stack (ElasticSearch, Logstash, Kibana), 9200-9300 TCP. Unfortunately AWS security groups cannot be changed post-launch (on the fly) on EC2 unless you go for VPC hosting (more expensive). We want open ports in advance, we can firewall/ACL them later.
- [x] Maybe open port range for bittorrent tracker(s) too, same reason as above.
- [x] Remove "playbook" from the repo/role name.
- [x] Change license to GPLv3 (unless it is forked from another project).

That's it for now, looking forward to have an instance running from this role and see BioStars2 core up and running next week!

@satra, @nicholsn

**Comment by puntonim** [comment]
I've opened ports 9200-9300 and 6881-6889 https://github.com/nimiq/ansible-biostar/commit/97b340b6e9a42f4d2c2d50b1d52fb3a85dd61636
Btw you can open/close ports on the fly by editing the Security Group of a running instance or changing to another Security Group, I've just done it myself.

**Comment by brainstorm** [comment]
Have you tried connecting to the service itself? Big difference. Can be
changed but no effect (cannot connect to newly defined port) unless they
are VPC.

**Comment by puntonim** [comment]
Well, maybe I didn't get it right... I launched an instance with only port 80 open, run Django on port 80 and I could connect to <IP>:80. Then I edited the associated Security Group on the fly opening port 90, run Django on port 90 and could connect to <IP>:90.

**Comment by brainstorm** [comment]
You're right, elasticsearch tricked me again with its tcpv6 default policies:

http://slacklabs.be/2012/04/02/force-Elastic-search-on-ipv4-debian/

**Comment by puntonim** [comment]
All done!
