### ISSUE TITLE
Errors from Docker webapp container log

### ISSUE THREAD

**Issue by puntonim** [puntonim/ansible-biostar#8]
root     16251  0.0  0.0    188    32 ?        S    11:12   0:00 /usr/bin/runsvdir -P /etc/service log: ......................................................................................................................................................................................................................chown: missing operand after 'root:adm' Try 'chown --help' for more information. createdb: database creation failed: ERROR:  database "XXX" already exists ...........

**Comment by puntonim** [comment]
No idea about the chown problem, I need further investigation.
While about the database I know: when the `webapp` container starts/restarts it tries to create the database required by Django. If it fails, it means that the database already exists and this info is used later on to skip some steps: https://github.com/nimiq/ansible-biostar/blob/master/roles/docker_webapp/templates/run_webapp.sh.j2#L29

But you raised 2 great points here:
- avoid logging this error;
- the webserver in the `webapp` container is run by `root` and the code is mounted to `/root/biostar`.
  I guess the path is again a violation of FHS and also running a webserver as root is a security issue (even tho it is in a isolated Docker container).

What do you recommend @brainstorm?

**Comment by brainstorm** [comment]
1. Logging the error to a file under the hosts's `/srv/logs`, for instance, is totally fine. The problem is showing it up while running `ps aux`. It should not end up on the shell's `$0` (running process name).
2. Even if the code runs inside a docker container, it is preferable to run processes as `www-data` instead of `root`.

**Comment by puntonim** [comment]
Ok, so TODO list in `webapp` container:
- Edit the command to create a new db such that stderr is redirected:  
  `createdb ... &> alogfile.log`  
  or: `createdb ... >/dev/null 2>&1`  
  https://github.com/nimiq/ansible-biostar/blob/master/roles/docker_webapp/templates/run_webapp.sh.j2#L28
- Create the user `www-data`, move the mountpoint of the codebase volume to `/var/www/biostar` or `/srv/biostar` and run the webserver as user `www-data`

**Comment by brainstorm** [comment]
Also please try to send the webapp logs to the host's `/srv`, I can only see the logs from the postgresql container in production:

```
ubuntu@neurostars-org:~$ ls /srv/docker-volumes/
pgdata
```

**Comment by puntonim** [comment]
Logs for `webapp` are already in:
`/srv/biostar-codebase/live/logs/`
I used that folder because it is already used somewhere in the biostar codebase. Is that ok?

PS: you can also see some logs with `docker logs webapp` (from the host)
http://docs.docker.com/reference/commandline/cli/#logs

**Comment by brainstorm** [comment]
Application logs are fine to be left there, but I cannot see accesses to the webserver (access.log-like entries). I guess that logging has not been enabled in `waitress`?

Thanks @nimiq!

**Comment by puntonim** [comment]
Waitress logging is not really a standard logging system like Nginx or Apache. Which is understandable because waitress is actually just python code. It logs to the root logger, so I had to configure a root logger in the biostar codebase to log to a file:
https://github.com/nimiq/ansible-biostar/blob/master/roles/docker_webapp/files/biostar/settings/logger_production.py#L62

Btw, I had a quick look at waitress [logging page](http://waitress.readthedocs.org/en/latest/#logging) and inspected the source code and what I found is that:
- waitress logs only errors (even if you set the logging level to INFO or DEBUG), so you cannot get an access.log in Apache/Nginx-style;
- using the logger named 'waitress' instead of the root logger did not work (even tho this is what they say in the official doc).

Anyway I might be wrong, but for sure this issue requires some attention and some time allocation,

To me a good improvement could be introducing Nginx as reverse proxy in the the same container. Nginx will take care of serving static files, serving python code via waitress (through a unix socker), logs. If you agree I'll open a new issue/enhacement.

**Comment by brainstorm** [comment]
Thanks for looking into that @nimiq. that's definitely an issue for us since logs are very interesting tool to profile scientific communities and keep improving the system. Even if google analytics provides some good insight already, we're losing valuable data (IP's, for instance) that we might use in the future. 

I would say thumbs up for nginx issue, we need this and it's not low-prio.

**Comment by puntonim** [comment]
Done f43098ea309c12dfbacc5903a07d1c18df41c2c5.
Logs are in place.
The chown error was a bug in phusion/baseimage and they solved it.
The database creation failed error has been solved.
